### ISSUE TITLE
Design for the crossposting service

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos-crossposting-service#1]
We need to design the UI for the cross-posting service. The website let's you log in with Twitter and then link various nostr accounts to your Twitter account. Once that happens whenever a new note is posted to those nostr identities it will be cross-posted to your Twitter profile.

What we need to accomplish:
- user needs to be able to open the website and learn what it does / how it works (I can write a description)
- user needs to be able to click a button to log in with Twitter
- a logged-in user should be able to see the name of the Twitter account they are logged in with
- a logged-in user needs to be able to see a list of their linked npubs
- a logged-in user needs to be able to unlink one of the linked npubs
- a logged-in user needs to be able to link a new npub

A very crude sketch just to see what components would be needed as described above, not to inspire the layout/design (missing "delete npub" buttons):
![2023-10-06 17:05:12](https://github.com/planetary-social/nos-crossposting-service/assets/1935975/36877896-dc59-499c-946c-b502c44c5f14)

It would also be cool to have some links to our website, to the Gihub repository with the service etc.

**Comment by Chardot** [comment]
Here's a preview of Nos X Connect on desktop:

![Image](https://github.com/planetary-social/nos-crossposting-service/assets/477835/9769c6df-f333-42f1-b37f-acadbf2ebc85)

also on mobile:

![Image](https://github.com/planetary-social/nos-crossposting-service/assets/477835/ff1fe9b4-3c3c-409e-b2da-2b426a2cad99)


and the [complete user flow](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=3183%3A19157&mode=design&t=W1p2Og5ou94l0lPm-1) on Figma

**Comment by boreq** [comment]
I think this can be closed, I still need to correct some things but there is a ticket for it here #17.
