### ISSUE TITLE
Purple pages lookups fail often

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos-crossposting-service#48]
I don't know why but purple pages lookups fail often so we either need to cache more aggressively so that caches persist between service restarts or fix a bug we may have in that code.

**Comment by mplorentz** [comment]
Maybe this will get better since Pablo is migrating it to a better server.

**Comment by boreq** [comment]
I found at least one bug in my code which was really stupid, it affected all `REQ`s to relays.

**Comment by boreq** [comment]
With some fixes we should have more successful lookups and also reduce the number of pointless lookups with a low chance of success. I will check the graph in an hour and two and if everything will be fine I will close this.

**Comment by boreq** [comment]
Things look good.

![Image](https://github.com/planetary-social/nos-crossposting-service/assets/1935975/decf8b50-567c-4aa1-b46d-e6a038a98da1)
![Image](https://github.com/planetary-social/nos-crossposting-service/assets/1935975/a04e1957-965a-4c35-a2bc-6624187f9af6)
